package base;
import java.io.*;

public class User implements Comparable<User>,Serializable{
	private int userId;
	private String userName;
	private String userEmail;	
	
	public User(int id,String name,String email){
		this.userId=id;
		this.userName=name;
		this.userEmail=email;
//		System.out.println("User [userId="+userId+","+"userName="+userName+","+"userEmail="+"userEmail"+"]");
	}
	public void setId(int id){
		this.userId=id;
	}
	public String getUserName()
	{
		return this.userName;
	}
	public void setName(String name){
		this.userName=name;
	}
	public void setEmail(String email){
		this.userEmail=email;
	}
	public String toString()
	{
		String line="User [userId="+this.userId+","+"userName="+this.userName+","+"userEmail="+this.userEmail+"]";
		return line;
	}
	/**
	 * hascode and equals are generated by Eclipse
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + userId;
		result = prime * result
				+ ((userName == null) ? 0 : userName.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (userId != other.userId)
			return false;
		if (userName == null) {
			if (other.userName != null)
				return false;
		} else if (!userName.equals(other.userName))
			return false;
		return true;
	}
	@Override 
	public int compareTo(User u)
	{
		if(this.userId>u.userId)
			return 1;
		else if(this.userId==u.userId)
			return 0;
		else
			return -1;
	}
	
	

}
